### ISSUE TITLE
请问这个能否用于Windows 8/10 的Metro UI App?

### ISSUE THREAD

**Issue by 171621** [v2ray/v2rayN#1]
Windows 8/10 的Metro UI App因为用的是UWP因此与localhost隔离了。必须要类似VPN的协议才能代理，请问这个工具能否用于Windows 8/10 的Metro UI App?

**Comment by qingyede** [comment]
uwp应用由于安全限制，需要手动添加代理例外
参考http://blog.csdn.net/wtwsgs/article/details/51333912
然后v2rayN是一个图形用户界面，你尝试后如果不行去这里提交下
https://github.com/v2ray/v2ray-core

**Comment by DarienRaymond** [comment]
v2ray-core 不会负责操作系统相关的东西，这些配置应该放在平台相关的客户端中。

**Comment by qingyede** [comment]
了解，Windows 8/10 的应用现在上网友现成的解决方法，google下自然就解决了
