### ISSUE TITLE
我的显示连上了，为什么没有用呢？连不上外网

### ISSUE THREAD

**Issue by aiyce** [v2ray/v2rayN#10]
![tim 20170730084333](https://user-images.githubusercontent.com/19799164/28749711-57c0b1ca-7503-11e7-9399-045dc8d5f551.png)
![tim 20170730084343](https://user-images.githubusercontent.com/19799164/28749712-57c57d90-7503-11e7-97c3-90b5c807311b.png)
![tim 20170730084354](https://user-images.githubusercontent.com/19799164/28749713-57ecfa46-7503-11e7-9fe4-9bae98eedae5.png)
谢谢！！！

**Comment by aiyce** [comment]
![tim 20170730084548](https://user-images.githubusercontent.com/19799164/28749718-890594e4-7503-11e7-9019-2c93f475ba78.png)

**Comment by Fengzhiying2017** [comment]
确认你的配置都没问题并和服务器一致？

**Comment by aiyce** [comment]
什么配置？？？？

**Comment by aiyce** [comment]
@Fengzhiying2017 什么配置？？？？

**Comment by aiyce** [comment]
@Fengzhiying2017 如果说是输入的uuid什么的肯定是对的

**Comment by Fengzhiying2017** [comment]
还有其他参数，你把服务端和客户端的配置json贴出来看下，v2rayN可以将服务器导出为“客户端配置”

**Comment by aiyce** [comment]
@Fengzhiying2017
 {
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 82,
    "listen": null,
    "protocol": "vmess",
    "settings": {
      "auth": null,
      "udp": false,
      "ip": null,
      "clients": [
        {
          "id": "03042ad7-6316-46a0-8473-65768b0f1fb2",
          "alterId": 64,
          "security": null
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}

**Comment by aiyce** [comment]
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "hk.ohmyss.win",
          "port": 82,
          "users": [
            {
              "id": "03042ad7-6316-46a0-8473-65768b0f1fb2",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        },
        {
          "type": "chinasites",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": null
        },
        {
          "type": "chinaip",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": null
        }
      ]
    }
  }
}

**Comment by Fengzhiying2017** [comment]
udp设置两边统一一下试试

**Comment by aiyce** [comment]
@Fengzhiying2017 udp怎么设置啊？  我能测试出延迟，就是不能代理国外网站，是不是还要设置其他什么东西？  不是学电脑专业的，弄得有点乱啊。。。

**Comment by aiyce** [comment]
@Fengzhiying2017 我udp改了，现在都是false，还是没有用。。。。

**Comment by aiyce** [comment]
@Fengzhiying2017 谢谢，我连上了，用了SwitchyOmega。。。我还以为这个和ss一样开了自己代理呢，尴尬。。。

**Comment by Fengzhiying2017** [comment]
解决了就好，这个在客户端使用方便性上还有待开发
