### ISSUE TITLE
期待增加可切换为 0.0.0.0 的监听功能

### ISSUE THREAD

**Issue by theringe** [v2ray/v2rayN#12]
您好，比较了很多 GUI 软件还是觉得这个好用，我本身有在使用 VM ，有时也会希望 guest 实例能够使用宿主机的本地代理，然而本地代理通常都是监听 127.0.0.1 上的端口，导致 LAN 中的其他主机都无法共用这个代理，我现在是使用端口转发软件解决的，但还是期待软件原生就支持这各功能，万分感谢。

**Comment by d4boy** [comment]
https://github.com/v2ray/v2rayN/releases/tag/1.12 已支持

**Comment by theringe** [comment]
太实用了，万分感谢！
