### ISSUE TITLE
关于路由设置的问题

### ISSUE THREAD

**Issue by Izumiko** [v2ray/v2rayN#13]
v2ray支持的domain类型的格式有三个，纯字符串、正则表达式、子域名。但在v2rayN中只有纯字符串形式能够生效，其他两种在config.json中并未添加上。
这是功能还未实现还是bug？

**Comment by d4boy** [comment]
未实现此功能

**Comment by Izumiko** [comment]
好吧，只用纯字符串也行，反正这里填的域名也不多
