### ISSUE TITLE
发现使用mkcp协议时软件的一个小问题

### ISSUE THREAD

**Issue by ppss1806** [v2ray/v2rayN#14]
在设置完成mkcp协议后测试发现速度较慢，并在服务器端加大uplinkCapacity的值，发现问题依旧，仔细阅读文档后发现是需要服务器和客户端分别设置并取最小值，因而开始设置客户端的值，发现默认配置的是12，当修改后重新启动，软件会自动的把值改回12，希望能改善一下。

**Comment by MAGE2X** [comment]
貌似是所有kcp的设置都强制默认属性的，找不到可以设置的地方。
于是我只好去改服务端的配置了

**Comment by d4boy** [comment]
https://github.com/v2ray/v2rayN/releases/tag/1.13
