### ISSUE TITLE
提2个建议

### ISSUE THREAD

**Issue by liangxyz** [v2ray/v2rayN#15]
首先感谢作者的好软件，速度非常快。我使用了这个GUI客户端，发现2个不如人意的地方，希望和作者探讨下。
1.V2RAYN 添加服务器的时候，我发现不能详细设置mKCP的有关参数，导致和我服务器的参数不一致，速度很慢。我使用程序自带的导入配置文件功能，发现导入以后，我配置文件的mkcp参数会被覆盖。

2.建议添加一个导出服务器配置的功能，我今天刚开始使用的时候，自己手动修改服务器配置，发现配置文件格式错误，服务器端无法启动。后来发现这个gui客户端，可以比较方便的设置各种参数，生成客户端配置，那么我就想，按照客户端配置生成服务器端应该也没有问题吧？这样就不用手动修改了，很方便。

最后还是感谢作者的软件，谢谢你！

**Comment by d4boy** [comment]
1. https://github.com/v2ray/v2rayN/releases/tag/1.13
2.已有
