### ISSUE TITLE
Warn about SSL key/cert when choosing TLS

### ISSUE THREAD

**Issue by henrypijames** [v2ray/v2rayN#17]
Following some tutorials for quick setup, I configured my v2ray client in v2rayN and exported the config to the server, but it didn't work. Activating debug logging revealed that I chose HTTP obfs with TLS, but didn't generate SSL key/cert for the server.

v2rayN should warn the user that SSL key/cert are needed on the server for TLS to work, and preferably even add a button to generate self-signed key/cert.

**Comment by d4boy** [comment]
will not do such a features
because the tls are advanced usage, do it yourself

**Comment by henrypijames** [comment]
But at least you  should the user when exporting server config with TLS enabled? Because the config file generated doesn't even have a `tlsSettings` section. In other words, it's guaranteed not to work on the server.
