### ISSUE TITLE
Do not use `text/html` for HTTP response

### ISSUE THREAD

**Issue by henrypijames** [v2ray/v2rayN#18]
When a server is configured to use HTTP obfs, v2rayN generates a config file that uses the following content type for HTTP response:
```
"Content-Type": [
  "application/octet-stream",
  "application/x-msdownload",
  "text/html",
  "application/x-shockwave-flash"
],
```

Should `text/html` really be there? The other three are binary, but HTML is plain text, and it is immediately obvious to anyone looking at the data stream (assuming HTTP obfs is used without TLS or WebSocket) that following an HTTP header declaring `Content-Type: text/html`, the response body is clearly not plain text.

For the same reason, Flash is easily falsifiable as well. Maybe we should only use content types that are binary and not easily identifiable.

**Comment by d4boy** [comment]
https://github.com/v2ray/v2rayN/releases/tag/1.14
