### ISSUE TITLE
Trim whitespaces when parsing HTTP obfs domains

### ISSUE THREAD

**Issue by henrypijames** [v2ray/v2rayN#19]
Specifying `domain1.tld, domain2.tld, domain3.tld` as HTTP obfs domains leads to this in config file:
```
"Host": [
  "domain1.tld",
  " domain2.tld",
  " domain3.tld"
],
```

The leading space - or any spaces, for that matter - should be trimmed since whitespaces are not allowed in domain names anyway.

**Comment by d4boy** [comment]
https://github.com/v2ray/v2rayN/releases/tag/1.14
