### ISSUE TITLE
关于生成服务端和客户端配置的问题

### ISSUE THREAD

**Issue by GEM7** [v2ray/v2rayN#2]
在V2rayN 1.8版本中在编辑配置中的”**TCP伪装域名（host）**“中填写多个域名后，导出成服务端配置进行查看时发现json文件中相关字段为
`"Host": [”a.a,b.b,c.c“],` 
其中的域名似乎是被合成整个字符串;但是从[官方网站](https://www.v2ray.com/chapter_02/transport/tcp.html)上对HTTP伪装的相关的相关说明上看，这个Host键后面跟的是一个数组，也就是
`"Host":["a.a","b.b","c.c"]`
V2rayN的这个地方是不是个BUG？

**Comment by dboy-xyz** [comment]
确实是存在这个问题，现在不支持填写多个域名伪装，只能是一个
可能会在下个版本修正

**Comment by GEM7** [comment]
谢谢你的回答！

**Comment by dboy-xyz** [comment]
1.9版已经增加了多个域名伪装
