### ISSUE TITLE
1.13加入的privoxy代理与原有的http代理之间有什么区别呢？

### ISSUE THREAD

**Issue by Fengzhiying2017** [v2ray/v2rayN#23]
如题，privoxy加入后感觉很好用，能自动把socks代理转换为http代理，但是与v2rayN原有的http代理有什么区别与联系呢？感觉开启privoxy后原来的http代理没有作用了。

**Comment by d4boy** [comment]
core自带的http有点问题
所以改用ss的方式换成privoxy

**Comment by Fengzhiying2017** [comment]
1.15版已经下载使用，去掉了v2ray自带的http选项，完全使用privoxy做http代理，感谢快速更新，提点建议：
1、http代理端口能否完全自定义或随机？避免传输时特定的http端口请求导致产生特征。
2、ss客户端与privoxy之间貌似有端口映射，启用系统代理时，自动设置的http端口号与ss的socks端口号相同，现在v2rayN是直接设置的privoxy端口号，建议与ss模式一致，对普通用户来与更容易理解，相当于privoxy对用户来与是透明的。
3、PAC功能很实用，建议加入从网址更新pac选项，也可以由用户增加条目。
另外，设置界面的对齐稍微优化一下，基础标签的“启用系统代理”放到托盘右键菜单，操作更方便。
以上，谢谢！

**Comment by d4boy** [comment]
1.在不停的调整中
2.和ss类似但是有不同，因为core是我们不能控制的，只能尽量
3.功能会慢慢加

**Comment by Fengzhiying2017** [comment]
期待不断更新^_^
