### ISSUE TITLE
本地监听端口2

### ISSUE THREAD

**Issue by standoun** [v2ray/v2rayN#27]
建议保留本地监听端口2的设置，这样可以自定义socks和http端口；

**Comment by d4boy** [comment]
原来是使用core自带的http，但是有点问题，所以现在只需要一个socks就够了，暂时不开放
如果需要请说明使用场景

**Comment by standoun** [comment]
谢谢，我自己在配置文件里手动加上就可以了

2017年8月23日 07:54，"d4boy" <notifications@github.com>写道：
