### ISSUE TITLE
可以设计一个开关，快速切换全局代理吗？  就是所有本地连接都走V2RAY  感谢~~~

### ISSUE THREAD

**Issue by mvdfish** [v2ray/v2rayN#6]
可以设计一个开关，快速切换全局代理吗？  就是所有本地连接都走V2RAY  感谢~~~

**Comment by d4boy** [comment]
先说$$功能，在Windows上系统设置时，会有一个“启用系统代理”的选项，如果启用该选项，那么软件会在IE的Internet选项--连接--局域网设置里添加localhost:1080。这样，IE和其他的支持这种代理设置的软件就会自动遵循设置。事实上，支持系统代理的软件非常少，一般来说只被浏览器普遍支持。

所以你可以在v2ranN的设置里面开启一个http，然后填入到ie里面去就可以支持了。
然后这个方式支持的软件太少，暂时不会搞

**Comment by Fengzhiying2017** [comment]
比如谷歌sync软件，开了ss默认就直接联网了，用v2rayN就不行，可能像ls说的那样再配置http代理也能达到一样的效果，但不是还得切换么？感觉就是ss一运行，系统里的软件就都可以通过ss代理了（全局），如果选pac，还能区分国内外流量

**Comment by Fengzhiying2017** [comment]
希望v2ray的客户端也做到ss客户端那么傻瓜化

**Comment by d4boy** [comment]
下一个版本增加http系统代理

https://github.com/v2ray/v2rayN/issues/8

**Comment by Fengzhiying2017** [comment]
@d4boy 辛苦了！希望下一版实现v2rayN启动后，增加右键开关切换“启用系统代理”，自动为应用设置代理，然后根据不同的应用决定走socks还是http，协议的转换最好在v2rayN内部进行（目前socks和http是分别设置，互相独立的），也可以像ss那样释放一个专门的http代理程序与主程序通讯，用户只关注一个统一的代理端口就可以了，这样就不用为不同代理协议的应用分别设置不同端口了。
建议右键增加选项“系统代理模式”，子菜单有：路由模式和全局模式，然后在v2rayN的软件全局“设置”（可放在右键“关于”菜单上面）里去设定“路由规则”，即现在的“中国IP”，“中国网站”以及将来其他的路由规则在这里设定好后，通过右键菜单即可一键切换路由与全局。
另外，ss客户端即使关闭“启用系统代理”，只要ss不退出，其他本来就不支持系统代理的应用貌似还是能通过ss代理，这个功能对普通用户很重要，本地完全自动化，只要开启v2rayN就可以代理大部分应用，不知能否实现。

**Comment by d4boy** [comment]
https://github.com/v2ray/v2rayN/releases/tag/1.12 已支持
你这个设计太复杂，初步是简单把http设置到ie的代理中，后面就和原来走一样的流程

**Comment by Fengzhiying2017** [comment]
@d4boy 
那现在支持不同代理协议的应用仍要手动设置不同的端口吗？不仅只是IE。

**Comment by d4boy** [comment]
windows中很多软件直接用的系统代理,甚至直接不能设置的,这些都直接走http就行了
剩下的能设置代理的,大部分都会有socks5可设置,这些是要自己设置的
