### ISSUE TITLE
来自局域网的连接被拒绝（reject）

### ISSUE THREAD

**Issue by 1349422030** [v2ray/V2RayN#6]
![image](https://user-images.githubusercontent.com/35253997/63179778-781c2200-c07f-11e9-8526-0a21d437c7b2.png)

在其他设备连接热点配置代理 http://192.168.137.1:10808 (192.168.137.1是打开热点后默认的本机ip）或者本地aria2指定代理为 http://127.0.0.0:10808 后，连接被拒绝

V2RayN配置如下
![image](https://user-images.githubusercontent.com/35253997/63179812-89652e80-c07f-11e9-82ae-21caac18793a.png)

![image](https://user-images.githubusercontent.com/35253997/63179951-ce896080-c07f-11e9-91f8-292deba52b99.png)

**Comment by Z4HD** [comment]
`10808` 端口需要使用支持 `socks5` 代理协议的软件连接。如需使用 `http` 代理协议连接，需要在软件托盘图标的右键菜单中点击启用http代理，http 代理的端口号通常为`本地监听端口号+1`，比如：`http://192.168.137.1:10809`
