### ISSUE TITLE
Dokoman-Door

### ISSUE THREAD

**Issue by jackwangshanghai** [v2ray/v2rayN#7]
能否添加Dokeman-Door的Gui支持，想做端口转发代理一些应用

**Comment by d4boy** [comment]
这些高级的功能还是自己写配置吧，你可以在N生成好的基础上自己加上
然后我可能会设计一个使用用户自定义的配置功能，还未想好

**Comment by jackwangshanghai** [comment]
貌似切换服务器的时候配置会被覆盖。。我感觉根据V2ray的思想还是 入口对出口映射比较好。因为有时候 转发的服务器和用的服务器不是一个。现在 V2rayN的 GUI能设置出口列表，但是不能设置入口列表（只有2个监听，而且统一出口），V2ray的映射 是通过 TAG的，感觉给每一个 出口和入口设置 tag，配置完 出口之后，可以对每一个入口设置出口。感觉这样 GUI设计起来也比较方便。

**Comment by d4boy** [comment]
我了解你的想法，在没有gui之前我也是这样用的
这样导致配置文件无比复杂，所以我才会用另外的文件存储多个出口配置(并且是覆盖v2ray自己的配置）
然后入口两个也是我考虑普通用户两个足够了，太多就复杂很多人就懵了

所以向类似你这种比较熟悉的用户还是自己写配置比较好
