### ISSUE TITLE
v2rayN能增加像ss那样自动注入软件代理设置的功能么？

### ISSUE THREAD

**Issue by Fengzhiying2017** [v2ray/v2rayN#8]
在网上找到一段文字，是这样介绍shadowsocks的：
https://fanzheng.org/archives/2
“在Windows上系统设置时，会有一个“启用系统代理”的选项，如果启用该选项，那么软件会在IE的Internet选项--连接--局域网设置里添加localhost:1080。这样，IE和其他的支持这种代理设置的软件就会自动遵循设置。事实上，支持系统代理的软件非常少，一般来说只被浏览器普遍支持。

ss还有一个选项，就是“系统代理模式”，可以选择是“PAC模式”还是“全局模式”。因为毕竟有些网站我们是不想走科学上网的，比如国内网站。如果我们选“PAC模式”，那么ss会自动从PAC list中判断你访问的网站有没有被墙，只有被墙了才会走代理，其他的直连。

需要注意的是，ss在1080端口开启了SOCKS5代理，但是它为了兼容http代理模式，在8123端口使用ss_privoxy.exe开启了一个http代理。不仅如此，ss在1080端口也支持http代理。我们知道，IE的代理设置不论是PAC还是全局，都是只支持http代理的。也正式因为ss支持http方式，才能使IE以及一些其他不支持SOCKS5（但支持http代理）的软件科学上网。”

从以上文字来看，ss在本地开启后，即开启了socks和http代理，方便的地方在于用户直接在ss客户端上操作，就替代了在浏览器或其他软件中手动设置代理，从用户的角度感觉很方便，现在v2rayN也可开同一客户端同时开启socks和http代理，但必须手动在浏览器或软件设置，希望能增加类似ss这样启动后自动设置（或称“注入”）代理的功能，退出时自动恢复原有设置。

另外再请教一下，还有一些软件比如Backup and Sync from Google，我开启ss能自动连接到服务器开始传输文件，但只用v2rayN却怎么也设置不成功，该软件的代理设置只有两个选项：自动检测和直接连接，也不知道怎样才可以使该软件通过v2rayN代理。

也不知道需求描述清楚没有，现在的v2rayN确实是用过的v2ray客户端里最方便的一个，上面有些功能可能已经支持而我没有理解或不会用，请兄台予以指点！谢谢！

**Comment by Fengzhiying2017** [comment]
又查了一下资料，ss启动时会解压出ss_privoxy.exe，该文件作用是将socks代理转换为http代理，默认端口是8123，不过浏览器及需要http代理的软件还是只设定端口为ss的默认端口（如1080）即可，是否可理解为软件如果需要走http代理时，仍与ss主程序1080端口通讯，ss发现是http代理请求就转发给ss_privoxy.exe处理，收到代理数据后再转成socks协议发给ss主程序，这样不管是需要socks还是http代理协议的软件，只统一设定一个端口即可，上文提到ss在1080端口也支持http代理应该就是这个意思，否则同一个端口无法同时被两个程序监听吧。
v2rayN是否也可以借鉴一下这个思路，实现socks和http代理协议的相互转换？再加上自动注入软件代理设置的模块，相信对普通的终端用户体验要好很多，也更容易推广普及。

**Comment by Fengzhiying2017** [comment]
找到一张ss工作流程图：
https://i.imgur.com/sAKKSVj.png

**Comment by d4boy** [comment]
辛苦你写这么多了。。。
v2ray本身就支持http方式，不过不怎么稳定；然后外挂一个exe也不好；这些在一开始我都考虑过的。
如果你们真的这么需要http系统代理，下一个版本加上吧

**Comment by theringe** [comment]
分享一个我自己当前的决方法：
将 v2ray 的 inbound 改设置为 shadowsocks 服务器，outbound 则照旧，接着用原本的 shadowsocks GUI 软件新增一个配置连到 127.0.0.1 的 shadowsocks 端口，多一层转发。

这样就可以利用 shadowsocks GUI 软件的右键切换全局代理功能实现 v2ray 实际的全局代理，还附赠该软件其他的功能让用户端无感知，例如允许 LAN 中的其他电脑也可使用该代理、流量可视化图表、流量记录、正向代理、GFWList、自动负载平衡等等。

上述方法唯一的缺点就是无法任意切换 v2ray 配置，所以可以酌情使用。

**Comment by Fengzhiying2017** [comment]
@d4boy 
我们更应该感谢您做了这么好用、方便的GUI，期待下一版本的v2rayN实现http to socks的双向转换，目前版本的两个代理协议本身是相互独立的，但比ss好的一点是http代理端口是可以自行设定的，而ss是固定8123。
另外想请测试一下谷歌同步软件googledrivesync如何使用v2rayN客户端作代理，现在用ss能连接服务器同步，但v2rayN不行。下载地址：https://www.google.com/drive/download/

**Comment by d4boy** [comment]
https://github.com/v2ray/v2rayN/releases/tag/1.12 已支持
这个版本先不做很复杂的控制
大部分windows软件是自动使用ie的系统代理

**Comment by d4boy** [comment]
https://github.com/v2ray/v2rayN/releases/tag/1.13

**Comment by Fengzhiying2017** [comment]
@d4boy 1.13很好用，谷歌的同步软件现在也没问题了。
