### ISSUE TITLE
最新版本V2rayN 服务端配置文件导出有问题

### ISSUE THREAD

**Issue by roy63258015** [v2ray/v2rayN#9]
刚刚下载最新版1.11配置后导出服务端配置文件，json配置文件里产生大量null参数，客户端导出正常，老版本1.10服务端和客户端导出正常

**Comment by d4boy** [comment]
最好能提供服务端配置文件全文

**Comment by d4boy** [comment]
文件中的null并不会影响，如果你的配置不行，可以帖出看看
